### ISSUE TITLE
Bundle ping executable with our app

### ISSUE THREAD

**Issue by andrewkim823** [andrewkim823/MySpeedTest#31]
We have seen issues with some phones where the default ping executable cannot be executed. This problem is not present in traceroute because it is bundled with our app.
Cross-compile a statically linked ping from source and bundle it with our app.

**Comment by andrewkim823** [comment]
Bundling the executable might not be the best solution.
Look into Android NDK for better compatibility.

**Comment by leecom3025** [comment]
Android NDK is basically building executable binary.
If you need, I can make one for v5 and x86 right now.

**Comment by andrewkim823** [comment]
In that case, can you cross-compile ping and traceroute for v5 and x86 (statically linked)?

**Comment by leecom3025** [comment]
yes boss on my way!

**Comment by leecom3025** [comment]
wait. 
for the traceroute, you are referring to tracert right?

**Comment by andrewkim823** [comment]
Traceroute. Tracert is the Windows version I believe.

**Comment by leecom3025** [comment]
confused I meant traceroute.

**Comment by andrewkim823** [comment]
sourceforge.net/projects/traceroute

**Comment by leecom3025** [comment]
I found tracepath (traceroute in rooted phone) in unrooted phone. 
I will cook them now.

**Comment by andrewkim823** [comment]
What's wrong with the regular traceroute? The code is already compatible with traceroute.

**Comment by leecom3025** [comment]
somehow Android refers to tracepath in aosp. I can change if you want to

**Comment by andrewkim823** [comment]
Traceroute is preferred

**Comment by leecom3025** [comment]
Done.

**Comment by andrewkim823** [comment]
Please do not merge the code or close issues yourself.
Neither ping nor tracepath were statically linked.
Tracepath is not compatible with our parser.

**Comment by leecom3025** [comment]
Sorry for the merge. 
Ping and tracepath (which recompiled to traceroute and somehow not included in the git commit) are executable binary. 
Statistically linked files are for system files whereas executable files are for the app to run within its own jvm.

**Comment by andrewkim823** [comment]
ARM executable added.
