### ISSUE TITLE
TrafficStats permission issues

### ISSUE THREAD

**Issue by andrewkim823** [andrewkim823/MySpeedTest#32]
Certain phones seem to deny access to data usage on applications other than MySpeedTest.
Look into what is causing this and try to find a workaround.

**Comment by leecom3025** [comment]
which phones (models)?

**Comment by andrewkim823** [comment]
Galaxy S3, the same phone that has been giving us issues with the ping executable denying permission.

**Comment by leecom3025** [comment]
i9300?

**Comment by andrewkim823** [comment]
I'll ask Arunesh the phone model to make sure before confirming that.

**Comment by andrewkim823** [comment]
Yes I can confirm that it is GT-I9300.

**Comment by leecom3025** [comment]
Can he send us setting screenshots with build and kernel version?

**Comment by andrewkim823** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/1480775/6175622/6cd488fe-b2c6-11e4-9487-75aa65e71ded.png)

**Comment by leecom3025** [comment]
Can Arnuesh show the result for the following command? 

$ls -l /proc/uid_stat/* 

From https://code.google.com/p/android/issues/detail?id=32410, it looks like old kernels (< 3.2) are causing the issue.

**Comment by andrewkim823** [comment]
Google API problem with certain devices. Cannot fix at the application level.
