### ISSUE TITLE
ThroughputActivity crashes

### ISSUE THREAD

**Issue by leecom3025** [andrewkim823/MySpeedTest#37]
3020        ActivityManager  I  START u0 {cmp=com.num/.view.activities.ThroughputActivity} from uid 10057 on display 0
  3020             AudioTrack  E  AudioTrack::set : Exit
  7285            Mobilyzer-3  D  API: Get API Singeton object...
  7285            Mobilyzer-3  D  API: API object not initialized...
  7285            Mobilyzer-3  D  API: constructor is called...
  7285            Mobilyzer-3  E  API-> startAndBindService() called false false
  7285            Mobilyzer-3  E  API-> bind() called 2
  7285         AndroidRuntime  D  Shutting down VM
  7285         AndroidRuntime  E  FATAL EXCEPTION: main
  7285         AndroidRuntime  E  Process: com.num, PID: 7285
  7285         AndroidRuntime  E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.num/com.num.view.activities.ThroughputActivity}: java.lang.IllegalArgument
                               Exception: Service Intent must be explicit: Intent { act=com.mobilyzer.MeasurementScheduler (has extras) }
  7285         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
  7285         AndroidRuntime  E  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
  7285         AndroidRuntime  E  at android.app.ActivityThread.access$800(ActivityThread.java:144)
  7285         AndroidRuntime  E  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
  7285         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
  7285         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:135)
  7285         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5223)
  7285         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
  7285         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Method.java:372)
  7285         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
  7285         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
  7285         AndroidRuntime  E  Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.mobilyzer.MeasurementScheduler (has extras) }
  7285         AndroidRuntime  E  at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1681)
  7285         AndroidRuntime  E  at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1710)
  7285         AndroidRuntime  E  at android.app.ContextImpl.startService(ContextImpl.java:1694)
  7285         AndroidRuntime  E  at android.content.ContextWrapper.startService(ContextWrapper.java:515)
  7285         AndroidRuntime  E  at com.mobilyzer.api.API.startAndBindService(API.java:212)
  7285         AndroidRuntime  E  at com.mobilyzer.api.API.<init>(API.java:124)
  7285         AndroidRuntime  E  at com.mobilyzer.api.API.getAPI(API.java:137)
  7285         AndroidRuntime  E  at com.num.view.activities.ThroughputActivity.onCreate(ThroughputActivity.java:63)
  7285         AndroidRuntime  E  at android.app.Activity.performCreate(Activity.java:5933)
  7285         AndroidRuntime  E  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
  7285         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
  7285         AndroidRuntime  E  ... 10 more
  3020        ActivityManager  W  Force finishing activity com.num/.view.activities.ThroughputActivity
  3020        ActivityManager  W  Force finishing activity com.num/.view.activities.MainActivity

**Comment by andrewkim823** [comment]
The newest version of My Speed Test must be tested to verify that this bug is patched.
